# MariaDB
db.url=jdbc:mariadb://127.0.0.1:3306/cursos
db.user=cursos
db.password=cursos


#db.url=jdbc:postgresql://db.rchmsntakypjybcettoq.supabase.co:5432/postgres
#db.user=postgres
#db.password=diplomadojavae19modulo2
